package Pojo;
// Generated 24 Jan, 2021 2:53:59 PM by Hibernate Tools 4.3.1



/**
 * Emp generated by hbm2java
 */
public class Emp  implements java.io.Serializable {


     private Long id;
     private String name;
     private String email;
     private String salary;
     private int age;
     private String gender;
     private String department;

    public Emp() {
    }

    public Emp(String name, String email, String salary, int age, String gender, String department) {
       this.name = name;
       this.email = email;
       this.salary = salary;
       this.age = age;
       this.gender = gender;
       this.department = department;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getSalary() {
        return this.salary;
    }
    
    public void setSalary(String salary) {
        this.salary = salary;
    }
    public int getAge() {
        return this.age;
    }
    
    public void setAge(int age) {
        this.age = age;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    public String getDepartment() {
        return this.department;
    }
    
    public void setDepartment(String department) {
        this.department = department;
    }




}


